name: Build and deploy Jekyll site to Azure Blob static page

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  jekyll:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: $-gems-$
        restore-keys: |
          $-gems-
    - uses: helaili/jekyll-action@v2
      with:
        jekyll_src: 'jekyll'
        target_path: '_site'
        build_dir: '_site'
        build_only: 'true'
    - name: chmod
      run: sudo chmod -R 777 /home/runner/work/undo.is/undo.is/_site/
    - uses: bacongobbler/azure-blob-storage-upload@main
      with:
        source_dir: '/home/runner/work/undo.is/undo.is/_site/'
        source_dir: 'jekyll/_site/_site/'
        container_name: '$web'
        connection_string: ${{ secrets.AZURE_CONNECTION_STRING }}
        #sas_token: ${{ secrets.SAS_TOKEN }}
        #account_name: ${{ secrets.STORAGE_ACCOUNT_NAME }}
        overwrite: 'true'
