name: Blob storage website CI

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: chmod
      run: sudo chmod -R 777 /home/runner/work/undo.is/undo.is/_site/
    - uses: azure/login@v2
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name undoissite --auth-mode key -d '$web' -s /home/runner/work/undo.is/undo.is/_site
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "undo-is-cdn-1" --name "undo-is-cdn-1" --resource-group "cameron.wisniewski_rg_Windows_eastus"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
